version: 1
formatters:
  standard:
    format: "%(asctime)s %(levelname)s %(name)s: %(message)s"
handlers:
  file:
    class: logging.handlers.RotatingFileHandler
    filename: logs/prefect.log
    maxBytes: 10485760
    backupCount: 5
    formatter: standard
loggers:
  prefect:
    level: INFO
    handlers: [file]
    propagate: true
